### ISSUE TITLE
wls_datasource: file puppet/type/wls_datasource/xaproperties not found on node

### ISSUE THREAD

**Issue by yadavnikhil** [biemond/biemond-orawls#120]
Could not autoload puppet/type/wls_datasource: file puppet/type/wls_datasource/xaproperties not found on node

Getting above issue when using wls_datasource module. 
Seems "xaproperties" missing from index.py

**Comment by biemond** [comment]
Do you have a puppet master with multiple environments then you can have this bug.

Move orawls and easy_type to the primary module location pup-1515 https://tickets.puppetlabs.com/browse/PUP-1515 when the Puppet master loads a Type, it searches the environment that the agent requested. When it loads providers for that type, it searches the default environment instead of the one the agent requested.

or see 1 of the other puppet master actions
https://github.com/biemond/biemond-orawls#puppet-master-with-orawls-module-key-points

indeed xaproperties is not yep part of the index.py see this pull request #110

**Comment by yadavnikhil** [comment]
Thanks. 

Yes, I have multiple environments for a single master.
For now my issue is resolved by running puppet agent on master. Once done, clients resolves the type & move ahead. 
Will follow the above for now.
