### ISSUE TITLE
wls_datasource modify.py.erb doesn't change password

### ISSUE THREAD

**Issue by JoshiiSinfield** [biemond/biemond-orawls#283]
files/providers/wls_datasource/modify.py.erb doesn't currently have the ability to change/set the password on the datasource.

**Comment by biemond** [comment]
indeed,

this is because password is a parameter and not a property so I cannot check the current value (protected) and compare that with the puppet config.

this means you need to change an other property (dummy change ) to set the password again on the modify. So I don't want to do this.

So if I got an way  to retrieve the current password I could check for it but for now you need to delete it (in the console or use present = absent ) and re-create it again with puppet.

thanks

**Comment by Raskil** [comment]
Hi Biemond,

I tried accessing the password for a datasource from WLST and I failed:
wls:/app01/serverConfig/JDBCSystemResources/IdGenDataSource/JDBCResource/IdGenDataSource/JDBCDriverParams/IdGenDataSource> get('Password')
Traceback (innermost last):
  File "<console>", line 1, in ?
  File "<iostream>", line 546, in get
  File "<iostream>", line 552, in raiseWLSTException
WLSTException: Error occurred while performing get : Error getting attribute Password : Access to sensitive attribute in clear text is not allowed due to the setting of ClearTextCredentialAccessEnabled attribute in SecurityConfigurationMBean.

Then again, i tried get(PasswordEncrypted') and I was able to get the encrypted password:
wls:/app01/serverConfig/JDBCSystemResources/IdGenDataSource/JDBCResource/IdGenDataSource/JDBCDriverParams/IdGenDataSource> get('PasswordEncrypted')
array('b',[123, 65, 69, 83, 125, 117, 90, 68, 71, 55, 102, 49, 50, 77, 55, 88, 72, 109, 117, 86, 114, 52, 67, 120, 65, 65, 116, 97, 67, 97, 100, 114, 72, 83, 111, 70, 77, 79, 48, 98, 48, 115, 48, 113, 55, 99, 57, 77, 61])

So we could either encrypt puppets plain text password and compare it to the already encrypted value in wlst or decrypt the wlst password and compre the two.
I tried the latter and was able to decrypt a datasource password with the script mentioned in this blogpost:
http://javaoraclesoa.blogspot.de/2013/08/wlst-obtaining-parameters-recovering.html

Maybe this helps a little?

regards

Raskil

**Comment by biemond** [comment]
I think the boot.properties of weblogic are 3des protected and very easy to retrieve it but others you need to be on the domain and it uses some machine info/salt.

it is not like an OS user where you can generate a hash, use that for the os user password and compare these values.

it can be done but I need to reverse engineer or crack it ( because of the specific machine info/salt) what not is really acceptable 

Thanks

**Comment by Raskil** [comment]
Doesn't the security provider of WLST take care of that? Here is a short example which does a comparison for me:

import os
import weblogic.security.internal.SerializedSystemIni
import weblogic.security.internal.encryption.ClearOrEncryptedService

def decrypt(agileDomain, encryptedPassword):
    agileDomainPath = os.path.abspath(agileDomain)
    encryptSrv = weblogic.security.internal.SerializedSystemIni.getEncryptionService(agileDomainPath)
    ces = weblogic.security.internal.encryption.ClearOrEncryptedService(encryptSrv)
    password = ces.decrypt(encryptedPassword)
    return password

connect('weblogic','welcome1', 't3://172.27.59.24:28001')

plaintextpwfrompuppet = 'welcome1'
domaindir = '/opt/wlsinstall/domains/domainname'
enpw = get('JDBCSystemResources/IdGenDataSource/JDBCResource/IdGenDataSource/JDBCDriverParams/IdGenDataSource/PasswordEncrypted')
enpwstring = ""
for b in enpw:
  enpwstring = enpwstring + chr(b)

pw = decrypt(domaindir, enpwstring)
print "Password from Puppet: " + plaintextpwfrompuppet
print "Decrypted from WLS: " + pw

if plaintextpwfrompuppet == pw:
   print "PWs are the same"
else:
   print "PWs are different"



Wiith that I'm able to compare a given plaintext password from puppet with the one set in the Datasource.

**Comment by biemond** [comment]
indeed this works, but I need to implement this on the index py script of the datasource and this should have access to the domain folder ( now it doesn't have this requirement) plus you can retrieve all the passwords when you run puppet resource wls_datasource.

So very appreciated, but Oracle should provide us some hash comparison.

**Comment by Raskil** [comment]
I agree on the first requirement but can't we work around the clear text storage by providing a read only property like the file types type property? There we could store the decrypted password as an sha512 hash. When doing the resource comparison we could easily hash the puppet password too and compare those.

I totally agree with you that Oracle should provide a hash comparioson but I'm not sure if they will ever do. Even if they do, it might not work with the versions we are currently using.

**Comment by biemond** [comment]
yeah that can work by generating a hash on both sides.

I only need to connect to the domain with WLST, retrieve the domain folder location, check if it is accessible. if not skip the password check, if so decrypt and make a hash

You can do it for WLST and I can do the ruby/puppet part. Or you can do both and send me a PR.

**Comment by Raskil** [comment]
I'm really not into the easy type nor the WLST stuff, so it would be hard for me to do a PR for this. But I could toss it over to Bert for implementation. In fact I already pointed him to the discussion :)

**Comment by hajee** [comment]
working on it.
