### ISSUE TITLE
Question - multiple instances of WLS 'orawls::weblogic'

### ISSUE THREAD

**Issue by standagh** [biemond/biemond-orawls#307]
Hi 
I have question - is it possible to have multiple instances of WLS installed on single host?

IMO it is not possible for single puppet run. 'orawls::weblogic' that installs WLS product is class. And AFAIK it is not possible to hove 2 instances of single class in puppet catalog with different parameters.

If I am correct - why was 'orawls::weblogic' implemented as class and not using defined type? Is there a reason for it? Will it be acceptable to change the definition?

**Comment by biemond** [comment]
Hi 

you are correct, I did this because nowadays it very easy to make a vm but when you got iron this can be hard or too costly.
  
What you can do it is making your own manifest (just fork it, strip it and make it a define) which install all the middleware homes and after that just continue with the orawls modules, the rest should work perfectly.

Hope this helps .

**Comment by standagh** [comment]
Thanks for the answer.

**Comment by biemond** [comment]
it is now supported
