### ISSUE TITLE
latest Oracle jdk 1.7_95 breaks certificate creation

### ISSUE THREAD

**Issue by michaeljquinn** [biemond/biemond-orawls#312]
Oracle have dropped MD5 support and it seems that cert creation is now broken

Certificates does not conform to algorithm constraints

For those with Oracle support see (Doc ID 2101401.1)

**Comment by biemond** [comment]
indeed,

where did you see it in orawls because a while ago I already update all the keystores of some vagrant boxes see 
https://github.com/biemond/biemond-orawls-vagrant-12.2.1/blob/master/certs.txt
and
https://github.com/biemond/biemond-orawls-vagrant-12.2.1/blob/master/keys/ca.conf

but you can also update the java.security 

MD5 now disabled for X509 Certificate validating
MD5 must not be used for digital signatures where collision resistance is required. To prevent the use of X.509 certificates that include an MD5-based digital signature algorithm, MD5 has been added to the jdk.certpath.disabledAlgorithms security property. Applications should upgrade or replace certificates that include an MD5-based digital signature.

Reversing this change is possible by removing MD5 from the jdk.certpath.disabledAlgorithms security property in the java.security file. This is not recommended.

JDK-8141287 (not public)

maybe remove md5 from jre/lib/security/java.security
jdk.tls.disabledAlgorithms=MD5, SSLv3, DSA, RSA keySize < 2048
jdk.tls.disabledAlgorithms=SSLv3, RC4, DH keySize < 768
