### ISSUE TITLE
Error: Failed to apply catalog: timeout on reading expected output from daemon process.

### ISSUE THREAD

**Issue by ltutar** [biemond/biemond-orawls#341]
I usually get with the second puppet run on the AdminServer the following timeout. Does anybody recognize this?

```
OPatch succeeded.

Info: index wls_user 
Info: Executing: wlstScript with action index
Info: domain found default
Info: Starting the wls daemon for domain default
Info: Executing wls-script /tmp/wlstCommonScript.py20160528-17104-18mua4i
Info: Executing wls-script /tmp/wlstScript20160528-17104-ml6vml.py with timeout = 120
Info: Connecting to wls on url t3://192.168.234.95:7001
Error: Failed to apply catalog: timeout on reading expected output from daemon process.
[root@wlsagent facts.d]#
```

**Comment by biemond** [comment]
then it probably crashed , this is a safety measure else you will be waiting for ever.

So it can be the adminserver should be restarted and this didn't happen. Or wls_user index went wrong or got a timeout because of some big ldap server.

Can you start puppet with --debug this should output all the data and used wlst script. With the failing script you can try it yourself to know where it fails.

Hope this helps

**Comment by JoshiiSinfield** [comment]
Hi,

we're also seeing this, but intermittently.

When it runs wls_user it seems to try and connect to the AdminServer twice...
see debug output below. I don't know if it's just log output, or whether it's actually connecting a second time but it's the only one that does seem to connect twice.

When it hangs, and supposedly times out it hangs just before the bold text is output... I think. It isn't failing at the moment for me to check!

any bright ideas?  we're currently running version 1.0.44 of orawls and 5.0.2 of orautils.

```
Debug:

Debug: Your environment has been set.

Debug:

Debug: Initializing WebLogic Scripting Tool (WLST) ...

Debug:

Debug: Welcome to WebLogic Server Administration Scripting Shell

Debug:

Debug: Type help() for help on available commands

Debug:

Debug: wls:/offline> wls:/offline> wls:/offline> wls:/offline> Connecting to t3://<<>>:10201 with userid weblogic ...

Debug: Successfully connected to Admin Server "AdminServer" that belongs to domain "domain".

Debug:

Debug: Warning: An insecure protocol was used to connect to the server.

Debug: To ensure on-the-wire security, the SSL port or Admin port should be used instead.

Debug:

**Debug: wls:/domain/serverConfig/> wls:/domain/serverConfig/> wls:/domain/serverConfig/> wls:/domain/serverConfig/> Connecting to t3://<<>>:10201 with userid weblogic ...**

Debug: Successfully connected to Admin Server "AdminServer" that belongs to domain "domain".

Debug:

Debug: Warning: An insecure protocol was used to connect to the server.

Debug: To ensure on-the-wire security, the SSL port or Admin port should be used instead.

Debug:

Debug: wls:/domain/serverConfig/> ~~~~COMMAND SUCCESFULL~~~~

```

**Comment by biemond** [comment]
it look strange but it good behaviour.

every resource have to do this because it can be that the adminserver is restarted by a subscribe, shutdown by fmwcluster, that's why need to be authenticate. Also wls_user is mostly the first resource type so in that case it will start the domain daemon for performance and log on -> that is why it is twice.

**Comment by JoshiiSinfield** [comment]
ah ok, that makes sense. I'll carry on trying to make some sense of why this is happening.

**Comment by JoshiiSinfield** [comment]
Hi,

I think we worked out what was happening with us...

Somehow our /tmp directory had lost the sticky bit, meaning that Ruby's tmpdir code was using the cwd instead of the /tmp directory. This then explained our intermittent behaviour, due to which directory we were running Puppet from, as some volumes have "noexec" mount option specified due to them being hardended platforms, meaning some of the wlst wasn't executed. 

(we think!)

Cheers,
Josh

**Comment by ltutar** [comment]
I do not have this problem anymore. I had this problem because fmwcluster was not working correctly on my machine. This issue may be closed if it is OK with the others.

**Comment by JoshiiSinfield** [comment]
indeed. We've also solved our problem and happy to close this.
