### ISSUE TITLE
Help/question around changes made but not applied until AdminServer restart

### ISSUE THREAD

**Issue by JoshiiSinfield** [biemond/biemond-orawls#345]
Hi @biemond 

I'm having some issues where machines, servers, datasources etc. are all being applied successfully through Puppet, and are visible from the Admin Console, however none of the items are visible when connecting to the AdminServer over WLST. 
The AdminServer is present in the "Restart Checklist" under the changes & restarts section and also I've set the Machines to be Plain NMType in hiera. They appear as Plain in the Admin Console, however they have an SSLException  UNTIL I restart the AdminServer, then they're correctly working as Plain, and are correctly visible in WLST.

Do you have any ideas what may be causing this? 
Any help appreciated!
Cheers,
Josh

**Comment by biemond** [comment]
Hi Josh,

it is part of the wls implementation.

this is because the edit() session only contains the actual information about the current state, this is logical because you want to change something and want to have the latest state. But for the wls types index phase I don't want to start an edit session because I don't want or need it.

So it would be nice if there is no difference between an edit session or not. 

This is why I added, subscribe to changes which automatically restart the adminserver to solve this.

Thanks Edwin

**Comment by JoshiiSinfield** [comment]
HI,

Thanks for getting back to me promptly!

It's strange,because we use the orawls::control resource but have never subscribed to it, and we've never had this problem before.

We must have gotten away with it somehow by only ever having one machine, which is usually SSL'ed - obviously being the default configuration before restarting AdminServer, therefore we've never had too much of a problem.

Now I'm creating multiple Plain Machines!

Thanks for your help. I'll stick a subscribe onto the AdminServer -> Machines and see what happens.

Cheers, Josh

**Comment by JoshiiSinfield** [comment]
Hi,

I've put a wls_adminserver resource in there, and notified it from the wls_machine instances and that's fixed it.

I've no idea why we haven't needed to do this before though.

Thanks for you assistance.

Cheers,
Josh

**Comment by biemond** [comment]
yeah, when you do something with something crucial with the adminserver, domain or security you should always have to restart. The rest is ok
