### ISSUE TITLE
Can't start multiple NodeManagers on 1036

### ISSUE THREAD

**Issue by bFekete** [biemond/biemond-orawls#347]
Can't start multiple weblogic nodemanagers on 1036 because it will start one NodeManager and think all NodeManagers are running.

According to:
https://github.com/biemond/biemond-orawls/blob/master/manifests/nodemanager.pp#L88

It only greps by weblogic.NodeManager. I was wondering if you could also grep it by the middleware home also.

Something like this: 
$checkCommand = "/bin/ps -ef | grep -v grep | /bin/grep 'weblogic.NodeManager' ' | grep '\-Dbea.home=${middleware_home_dir}'"

**Comment by biemond** [comment]
Ok,

why should you have multiple nodemanagers in 10.3.6 , it is not like 12c where you have 1 per domain. You have 1 per VM with wls 10.3.6, maybe you have multiple 10.3.6 middleware homes but still 1 nodemanager should be able to handle all domains.

what is your usecase?

**Comment by bFekete** [comment]
Sorry for my ignorance in Weblogic but we have multiple instances of Weblogic which all have different middleware homes. With that we have multiple domains in each instance and each instance has a nodemanager running.

**Comment by biemond** [comment]
ok, 

that makes sense. But it is not necessary if you move domains outside the mdw home and 1 nodemanager can handle all domains of multiple mdw homes. It is very basic piece of software and just use StartScriptEnabled=true and it will use the scripts of the domain to startup. Use the other nodemanager on the other mdw home as backup. Probably you need to nmenroll for the domains of the other mdw home 
Also we used to have the nodemanager running on a different OS account then the mdw install or use the ssh one instead of the java nodemanager.

Hope this helps.

**Comment by bFekete** [comment]
Alrighty, thanks for your help!
