### ISSUE TITLE
orawls and eyaml

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#437]
Hi Edwin,

How do I get eyaml to integrate with orawls module ?

I was able to install eyaml and integrate it with Puppet. But it does not seem to work if I had an encrypted key in common.yaml ( under orawls/data).

I am thinking the file "hiera.yaml" in orawls needs to be modified to get it to work but the format is so different, I am having a hard time getting it to work.

**Comment by biemond** [comment]
Hi,

under orawls/data is internal hiera and not something for customers ( off limits) and should never contain password, it is more for central location and differences between linux and solaris
you need to change the normal hiera with puppet like these ones
https://github.com/biemond/biemond-orawls-vagrant-12.2.1-puppet4/tree/master/puppet/hieradata

eyaml is puppet configuration and is more between puppet and hiera . it has nothing to do with orawls because puppet will just invoke the orawls define or class. orawls doesn't care where this value is coming from.

thanks

**Comment by userMar2017** [comment]
I see. In other words, store the encrypted password in local hiera configuration vs orawls.

Thanks for clarifying Ed.

**Comment by biemond** [comment]
you mean do it outside orawls. 
check this out http://www.craigdunn.org/2017/04/managing-puppet-secrets-with-jerakia-and-vault/
very cool and much better
