### ISSUE TITLE
Add additional arguments to mananged server

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#487]
Hi Ed,

After we complete the entire weblogic domain provisioning, ie after the admin server + managed servers are provisioned using orawls module, we would like to add a few arguments to the managed server (based on certain criteria). Is that possible via orawls module ? If so, how do we achieve it ?

**Comment by biemond** [comment]
like this on wls_server type

https://github.com/biemond/biemond-orawls-vagrant-12.2.1-puppet4/blob/master/puppet/hieradata/admin.example.com.yaml#L408

you can program it in a manifest based on your criteria

**Comment by userMar2017** [comment]
Correct. We are already using that for the "initial" setup. This is more of a post provisioning task. I am looking to "add" to the arguments. Can we still use the procedure you described ?

**Comment by biemond** [comment]
that is strange and not really the puppet way because you have different arguments defined on the same type and it won't work because the title can only be used once. So you need to do it with 1 type definitions and the 2nd puppet run and the next times you can use different arguments but you need to use a manifest instead of hiera in that case
