### ISSUE TITLE
orawls opatch

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#537]
Hi Ed,

I noticed that for every patch that is installed in WebLogic, there is a corresponding xml file 
ORACLE_HOME/inventory/patches/<PATCH_NUM>.xml

Is there anyway to use this information to prevent opatch from running again, say 

orawls::opatch {PATCH_NUM:
..
..
unless => ORACLE_HOME/inventory/patches/<PATCH_NUM>.xml
}

This will result in massive savings for us. Thanks in advance for your help.

**Comment by userMar2017** [comment]
Hi Ed,

Would like to hear your comment on this one.

**Comment by biemond** [comment]
Hi,

this in the central inventory? , does this also work for FMW 11g & wls 12.1.2. 
It has to work for all versions or we need to add some opatch version check.

thanks

**Comment by userMar2017** [comment]
Hi Ed,

Thanks for responding. I checked wls 12.1.2 and the files exists cos it uses opatch.
In 11g, I dont see these files. I suspect its because 11g uses bsu and not opatch. But since the class we are referring to is opatch, I dont understand how it works with 11g (since 11g uses bsu).

Now, since our entire environment uses 12c, this is not a problem for me. If I wanted to write my own opatch class to look for this file instead of opatch command, how could I go about it ? I would need to figure out how to create my own module first ? I suspect it wont be so easy.

**Comment by biemond** [comment]
Nice, we can add a check to the opatch , which first checks this folder first instead of lsinventory

**Comment by userMar2017** [comment]
That would be awesome Ed !

**Comment by userMar2017** [comment]
Hi Ed,

Were you able to get to this ?

**Comment by biemond** [comment]
Not yet. Enjoying the summer

**Comment by userMar2017** [comment]
:) What a co-incidence, I am on vacation too ... I will be back on Monday  ! Have fun Ed.

**Comment by userMar2017** [comment]
Hi Ed,

Hope you had a great vacation ! When you get a minute, can you please update on this request ?

**Comment by biemond** [comment]
Hi,

So I added a fact ora_mdw_opatch_patches with all the patches applied we can use that to skip it.

**Comment by userMar2017** [comment]
Great ! Should I pull down the latest and test ?

**Comment by userMar2017** [comment]
Hi Ed,

Checking to see if 2.0.17 contains this enhancement and whether the command below builds the fact list. Curious to know if it will run "opatch lspatches" as part of every run or whether it will be a one time task.

def get_opatch_patches(name)
  opatch_out = Facter::Util::Resolution.exec(get_su_command + get_weblogic_user + ' -c "' + name + '/OPatch/opatch lspatches"')
  return nil if opatch_out.nil?

**Comment by rrod157** [comment]
Hi Ed,

After updating it to 2.0.17, It still seem to run opatch command (I checked it by running puppet agent -t manually):

Debug: Prefetching prefetching resources for wls_opatch
Info: Oracle Interim Patch Installer version 13.2.0.0.0
Copyright (c) 2014, Oracle Corporation.  All rights reserved.


Oracle Home       : /appl/wl12c/Oracle/Middleware/Oracle_Home
Central Inventory : /appl/wl12c/Oracle/oraInventory
   from           : /home/ii00wl/oraInst.loc
OPatch version    : 13.2.0.0.0
OUI version       : 13.2.0.0.0
Log file location : /appl/wl12c/Oracle/Middleware/Oracle_Home/cfgtoollogs/opatch/opatch2018-11-13_21-44-49PM_1.log


OPatch detects the Middleware Home as "/appl/wl12c/Oracle/Middleware/Oracle_Home"

Nov 13, 2018 9:44:51 PM oracle.sysman.oii.oiii.OiiiInstallAreaControl initAreaControl
INFO: Install area Control created with access level  0
Lsinventory Output file location : /appl/wl12c/Oracle/Middleware/Oracle_Home/cfgtoollogs/opatch/lsinv/lsinventory2018-11-13_21-44-49PM.txt

--------------------------------------------------------------------------------

Interim patches (3) :

Patch  21983457     : applied on Tue Nov 13 21:28:06 MST 2018
Unique Patch ID:  19594444
   Created on 9 Dec 2015, 09:17:59 hrs PST8PDT
   Bugs fixed:
     18305935, 20523619, 21252292, 18671042, 18727635, 19703527, 21495475
     20758863, 21169554, 20080751, 19066738, 20798352, 22200449, 17012341
     18538501, 19339238, 20814890, 18432174, 20906638, 19268444, 22200523
     19928803, 19033547, 22248079, 18859387, 21746415, 18945422, 20985893
     18589879, 19953516, 19351700, 20169972, 19874466, 21756751, 19422493
     17702917, 18753794, 17968606, 18691894, 19917991, 18376812, 22200594
     18082758, 18428696, 19533331, 19973098, 19556868, 21069524, 19299358
     19852007, 19585666, 19459949, 16562029, 20206879, 19705162, 19265688
     18722098, 18276961, 18964349, 20333386, 19001915, 19988824, 18289179
     18729264, 19917893, 20266379, 18718889, 22247869, 18746515, 21615827
     20613957, 19879223, 19297004, 19942900, 18836900, 19668883, 19500276
     22175246, 19576633, 21516492, 20471785, 18968900, 19287842, 22200491
     21107126, 19790693, 19730967, 18912482, 18466848, 19287874, 17721032
     20323632, 20229977, 18481239, 19883023, 19936917, 18922324, 17394051
     19907066, 19080525

Patch  20215127     : applied on Tue Nov 13 21:28:06 MST 2018
Unique Patch ID:  19243665
Patch description:  "One-off"
   Created on 13 Aug 2015, 19:00:08 hrs UTC
   Bugs fixed:
     20215127
   This patch overlays patches:
     20741228
   This patch needs patches:
     20741228
   as prerequisites

Patch  20741228     : applied on Tue Nov 13 21:28:06 MST 2018
Unique Patch ID:  18985724
Patch description:  "JDBC 12.1.3.1 BP1"
   Created on 2 Jun 2015, 05:57:41 hrs PST8PDT
   Bugs fixed:
     20741228



--------------------------------------------------------------------------------

OPatch succeeded.

**Comment by biemond** [comment]
Hi I just added the fact with all the patches you can use that to skip it. You have to do this yourself

**Comment by rrod157** [comment]
is this an attribute that needs to be included in the orawls::opatch command? can you please guide us how this can be done?

**Comment by biemond** [comment]
You can make your own if statement around the patch command in the manifest 
https://puppet.com/docs/puppet/5.3/lang_facts_and_builtin_vars.html
Can check  if that works

**Comment by rrod157** [comment]
May I know the fact name again and how can i declare it for if condition?

**Comment by userMar2017** [comment]
Nothing shows up for that fact. Am I doing something wrong ?
<pre>
# facter -p | grep -i ora_mdw_opatch_patches
# 
</pre>

If I just search ora_mdw, a number of items are listed :
<pre>
# facter -p | grep -i ora_mdw  | wc -l
43
# 
</pre>

**Comment by biemond** [comment]
See      
https://github.com/biemond/biemond-orawls/blob/a86cadb6a52e4e7f99ac3cc9aeb6179c16ddfb92/lib/facter/orawls.rb#L150

You Will only see it during the puppet run or on the puppet master dashboard. it is a runtime fact not like a fixed one like os or cpu.

**Comment by userMar2017** [comment]
Oh, so can I do the following ? I need to do this in puppet not in Ruby.
<pre>
$installed_patches = $facts['ora_mdw_opatch_patches']
</pre>

**Comment by biemond** [comment]
I think so, can you add the info statements to orawls.rb and do a run to see all the output first. maybe it fails somewhere also you only have 1 mdw home or not

**Comment by userMar2017** [comment]
I dont have access to the server so I cannot modify orawls.rb.
But let me write a puppet code with the statement I provided earlier to see if it works.

I simply assumed that all facts would show up with facter. Bad assumption on my part, sorry about that !

**Comment by rrod157** [comment]
I've added these two lines in my puppet code:
$installed_patches = $facts['ora_mdw_opatch_patches']
notify {"Value of \$installed_patches is ${installed_patches}":} 

But I don't see any value being displayed:
Notice: Value of $installed_patches is

**Comment by biemond** [comment]
I see this 
```
==> admin: Info: -patches- 27912627;WLS PATCH SET UPDATE 12.2.1.3.180717
==> admin:
==> admin: Info: -patches- 26355633;One-off
==> admin:
==> admin: Info: -patches- 26287183;One-off
==> admin:
==> admin: Info: -patches- 26261906;One-off
==> admin:
==> admin: Info: -patches- 26051289;One-off
==> admin:
==> admin: Info: -patches hash- [{"patch_id"=>"27912627", "patch_desc"=>"WLS PATCH SET UPDATE 12.2.1.3.180717"}, {"patch_id"=>"26355633", "patch_desc"=>"One-off"}, {"patch_id"=>"26287183", "patch_desc"=>"One-off"}, {"patch_id"=>"26261906", "patch_desc"=>"One-off"}, {"patch_id"=>"26051289", "patch_desc"=>"One-off"}]
==> admin: Info: -all patches hash- {"/opt/oracle/middleware12c"=>[{"patch_id"=>"27912627", "patch_desc"=>"WLS PATCH SET UPDATE 12.2.1.3.180717"}, {"patch_id"=>"26355633", "patch_desc"=>"One-off"}, {"patch_id"=>"26287183", "patch_desc"=>"One-off"}, {"patch_id"=>"26261906", "patch_desc"=>"One-off"}, {"patch_id"=>"26051289", "patch_desc"=>"One-off"}]}
``` 
lets try your statement

**Comment by biemond** [comment]
```
Notice: Value of {/opt/oracle/middleware12c => [{patch_id => 27912627, patch_desc => WLS PATCH SET UPDATE 12.2.1.3.180717}, {patch_id => 26355633, patch_desc => One-off}, {patch_id => 26287183, patch_desc => One-off}, {patch_id => 26261906, patch_desc => One-off}, {patch_id => 26051289, patch_desc => One-off}]} is {/opt/oracle/middleware12c => [{patch_id => 27912627, patch_desc => WLS PATCH SET UPDATE 12.2.1.3.180717}, {patch_id => 26355633, patch_desc => One-off}, {patch_id => 26287183, patch_desc => One-off}, {patch_id => 26261906, patch_desc => One-off}, {patch_id => 26051289, patch_desc => One-off}]}
==> admin: Notice: /Stage[main]/Main/Node[admin.example.com]/Notify[Value of {/opt/oracle/middleware12c => [{patch_id => 27912627, patch_desc => WLS PATCH SET UPDATE 12.2.1.3.180717}, {patch_id => 26355633, patch_desc => One-off}, {patch_id => 26287183, patch_desc => One-off}, {patch_id => 26261906, patch_desc => One-off}, {patch_id => 26051289, patch_desc => One-off}]} is {/opt/oracle/middleware12c => [{patch_id => 27912627, patch_desc => WLS PATCH SET UPDATE 12.2.1.3.180717}, {patch_id => 26355633, patch_desc => One-off}, {patch_id => 26287183, patch_desc => One-off}, {patch_id => 26261906, patch_desc => One-off}, {patch_id => 26051289, patch_desc => One-off}]}]/message: defined 'message' as 'Value of {/opt/oracle/middleware12c => [{patch_id => 27912627, patch_desc => WLS PATCH SET UPDATE 12.2.1.3.180717}, {patch_id => 26355633, patch_desc => One-off}, {patch_id => 26287183, patch_desc => One-off}, {patch_id => 26261906, patch_desc => One-off}, {patch_id => 26051289, patch_desc => One-off}]} is {/opt/oracle/middleware12c => [{patch_id => 27912627, patch_desc => WLS PATCH SET UPDATE 12.2.1.3.180717}, {patch_id => 26355633, patch_desc => One-off}, {patch_id => 26287183, patch_desc => One-off}, {patch_id => 26261906, patch_desc => One-off}, {patch_id => 26051289, patch_desc => One-off}]}'
```

**Comment by userMar2017** [comment]
Other than adding "info statements to orawls.rb", is there any other way to troubleshoot ? We dont have access to the Puppet master server so making changes becomes very difficult.

**Comment by biemond** [comment]
no, but you can execute the opatch statements yourself to see  if that works at least

**Comment by userMar2017** [comment]
You mean like just opatch lsinventory ? That works fine Ed.

**Comment by biemond** [comment]
ok change orawls on your puppet master or go local on the box with puppet apply , ( no need for a puppet master)

**Comment by userMar2017** [comment]
I had them make the change (ie uncomment the info in the rb file) but it did not work. Its appears to be getting cached on the server I think. I deleted the local agent cache but it did not help. I guess I will need to do this the hard way but procuring a server, installing orawls locally and testing it out.

**Comment by userMar2017** [comment]
It was getting cached on another server ; that caching issue is resolved.

However, we are not setting any output from that piece of code. I even turned on debug using "puppet agent -t --debug"

**Comment by biemond** [comment]
you have to add those info statements to orawls.rb , info can be seen without --debug

**Comment by userMar2017** [comment]
Correct. I uncommented line 151 in orawls.rb ; ran "puppet agent -t" but did not notice anything. I ran "puppet agent -t --debug" and did not yield anything either.

**Comment by userMar2017** [comment]
Hi Ed,

I had someone with some programming knowledge take a look and he said that it was because it was looking for orainst and not finding it ?

Is the code hardcoded to look for oraInst.loc in /etc ?
In our case its in the home directory of the user
To test it, I copied it over to /etc folder and I see some information. Not what we need but at least its printing out something

**Comment by biemond** [comment]
oh really, 

/etc is the default (from oracle) maybe more goes wrong and can be slow 
but you can override it by setting a fact. 
```
for ora inst location: override_orainst_dir=[custom_path] or set FACTER_override_orainst_dir=[custom_path]

Set $puppet_os_user on some of the manifests or set this hiera variable puppet_os_user
```

**Comment by userMar2017** [comment]
Its odd that its not able to recognize where oraInst.loc is. But there is something else too because it should have worked when I copied it over to /etc.

I am trying to copy that ruby code and make changes to it. But I dont know ruby so its going to take me some time :(

**Comment by biemond** [comment]
hehe how can I know where you put it (this is run before your modules), that is why /etc is the general default unless you specify it with a fact.

**Comment by userMar2017** [comment]
What is surprising is that nothing else breaks :)  Thankfully, its not used much !

**Comment by userMar2017** [comment]
Ed, On a side node, were you at Oracle OpenWorld 2018 by any chance ?

**Comment by biemond** [comment]
it is more I added have double checks, I check if the mdw , product already exists by reading /etc/oraInst.loc plus read oraInventory. if so I skip install directly if not we have failback by checking dirs in the puppet resource but that is slower.

**Comment by rrod157** [comment]
Hi Ed,

I was able to view the fact by using these codes:
$ora_mdw_patchlist_array = $facts['ora_mdw_opatch_patches'][$wls_1213_middleware_home_dir]
notify {"Value of \$ora_mdw_patchlist_array is ${ora_mdw_patchlist_array}":}

Result:
Notice: Value of $ora_mdw_patchlist_array is [{patch_id => 21983457, patch_desc => }, {patch_id => 20215127, patch_desc => One-off}, {patch_id => 20741228, patch_desc => JDBC 12.1.3.1 BP1}]

However, I am having difficulty checking if the patch number is applied. Is there a way that I can simply compare the patch number against these value?

Notice: Value of $wls_1213_patch_id_generic is 21983457
Notice: Value of $wls_1213_patch_id_generic is 20741228
Notice: Value of $wls_1213_patch_id_generic is 20215127

**Comment by biemond** [comment]
hehe, 

you can try to use regex https://puppet.com/docs/puppet/5.3/lang_conditional.html#conditions

**Comment by rrod157** [comment]
regex wouldn't work on two variables. I managed to extract just all the patch_id using this command:

$ora_mdw_patchlist_hash = $facts['ora_mdw_opatch_patches'][$wls_1213_middleware_home_dir]
$test_patch_id = $ora_mdw_patchlist_hash.map |Integer $key, Hash $value| {
  $value['patch_id']
}
notify {"Value of \$test_patch_id is ${test_patch_id}":}

Result:
Notice: Value of $test_patch_id is [21983457, 20215127, 20741228]


after that, I created an 'if' condition around orawls::opatch

if ! ($wls_1213_patch_id_generic in $test_patch_id) {
  orawls::opatch
  ...
  ...
}

Result:
*Opatch command is gone.

**Comment by Joris29** [comment]
@biemond Hi i have an issue when trying to apply an opatch to wls.

Code:
`orawls::opatch {'27141906':
    ensure                                     => 'present',
    oracle_product_home_dir       => '/sysprogs/oracle/wls/122130',
    jdk_home_dir                          => '/sysprogs/oracle/java/current-jdk',
    patch_id                                  => 27141906,
    patch_file                                => '27141906',
    os_user                                    => 'oracle',
    os_group                                 => 'oinstall',
    download_dir                          => '/software/sysinstall/fmw/patches',
    puppet_download_mnt_point => '/software/sysinstall/fmw/patches',
    remote_file               => false,
    log_output                => true,
  }`

The patch is already extracted to a folder in /software/sysinstall/fmw/patches/27141906

[27141906.zip](https://github.com/biemond/biemond-orawls/files/3137693/27141906.zip)
This is the zipped file

The error i get is: Wls_opatch[/sysprogs/oracle/wls/122130:27141906]: change from 'absent' to 'present' failed: Could not set 'present' on ensure: Error while executing opatch command (file: C:/Users/vanacjo/.puppetlabs/bolt/modules/orawls/manifests/opatch.pp, line: 55)

**Comment by biemond** [comment]
Please show me the output of opatch to see what is going? Please run puppet in debug mode.

**Comment by Joris29** [comment]
@biemond I'm running it with bolt but today I started with a fresh instance and the patch file is not getting applied at all nor do I get an error and when I run:
 ./opatch lsinventory -jre /sysprogs/oracle/java/current-jdk/jre/

The patch is not shown

**Comment by Joris29** [comment]
@biemond I am now trying it on a local vm.

Setup:

orawls::opatch {'27141906':
    ensure                    => 'present',
    oracle_product_home_dir   => '/sysprogs/oracle/wls/122130',
    jdk_home_dir              => '/sysprogs/oracle/java/current-jdk',
    patch_id                  => 27141906,
    patch_file                => '27141906',
    os_user                   => 'oracle',
    os_group                  => 'oinstall',
    download_dir              => '/software/sysinstall/fmw/patches',
    puppet_download_mnt_point => '/software/sysinstall/fmw/patches',
    remote_file               => false,
    log_output                => true,
    orainstpath_dir           => '/sysprogs/oraInventory',
  }

but i still get:
Argument(s) Error... Patch Location not valid

Error: Could not set 'present' on ensure: Error while executing opatch command (file: /opt/puppetlabs/puppet/modules/orawls/manifests/opatch.pp, line: 55)
Error: Could not set 'present' on ensure: Error while executing opatch command (file: /opt/puppetlabs/puppet/modules/orawls/manifests/opatch.pp, line: 55)
Wrapped exception:
Error while executing opatch command
Error: /Stage[main]/Intris2::System::Wls/Orawls::Opatch[27141906]/Wls_opatch[/sysprogs/oracle/wls/122130:27141906]/ensure: change from 'absent' to 'present' failed: Could not set 'present' on ensure: Error while executing opatch command (file: /opt/puppetlabs/puppet/modules/orawls/manifests/opatch.pp, line: 55)


I ran puppet in debug:
Debug: Prefetching prefetching resources for wls_opatch
Info: Oracle Interim Patch Installer version 13.9.2.0.0
Copyright (c) 2019, Oracle Corporation.  All rights reserved.


Oracle Home       : /sysprogs/oracle/wls/122130
Central Inventory : /sysprogs/oraInventory
   from           : /sysprogs/oraInventory/oraInst.loc
OPatch version    : 13.9.2.0.0
OUI version       : 13.9.2.0.0
Log file location : /sysprogs/oracle/wls/122130/cfgtoollogs/opatch/opatch2019-05-20_12-42-16PM_1.log


OPatch detects the Middleware Home as "/sysprogs/oracle/wls/122130"

Lsinventory Output file location : /sysprogs/oracle/wls/122130/cfgtoollogs/opatch/lsinv/lsinventory2019-05-20_12-42-16PM.txt

--------------------------------------------------------------------------------
Local Machine Information::
Hostname: hg65g72.iconos.be
ARU platform id: 226
ARU platform description:: Linux x86-64


Interim patches (4) :

Patch  26355633     : applied on Mon May 20 10:50:00 CEST 2019
Unique Patch ID:  21447583
Patch description:  "One-off"
   Created on 1 Aug 2017, 21:40:20 hrs UTC
   Bugs fixed:
     26355633

Patch  26287183     : applied on Mon May 20 10:49:46 CEST 2019
Unique Patch ID:  21447582
Patch description:  "One-off"
   Created on 1 Aug 2017, 21:41:27 hrs UTC
   Bugs fixed:
     26287183

Patch  26261906     : applied on Mon May 20 10:49:24 CEST 2019
Unique Patch ID:  21344506
Patch description:  "One-off"
   Created on 12 Jun 2017, 23:36:08 hrs UTC
   Bugs fixed:
     25559137, 25232931, 24811916

Patch  26051289     : applied on Mon May 20 10:49:15 CEST 2019
Unique Patch ID:  21455037
Patch description:  "One-off"
   Created on 31 Jul 2017, 22:11:57 hrs UTC
   Bugs fixed:
     26051289



--------------------------------------------------------------------------------

OPatch succeeded.

Argument(s) Error... Patch Location not valid

Info: Oracle Interim Patch Installer version 13.9.2.0.0
Copyright (c) 2019, Oracle Corporation.  All rights reserved.


ZOP-50: The patch location is not valid because it may not exist (or) current user has no permission to access it. Please check the same.
Please check the arguments and try again.

OPatch failed with error code 135

Error: Could not set 'present' on ensure: Error while executing opatch command (file: /opt/puppetlabs/puppet/modules/orawls/manifests/opatch.pp, line: 55)
Error: Could not set 'present' on ensure: Error while executing opatch command (file: /opt/puppetlabs/puppet/modules/orawls/manifests/opatch.pp, line: 55)
Wrapped exception:
Error while executing opatch command
Error: /Stage[main]/Intris2::System::Wls/Orawls::Opatch[27141906]/Wls_opatch[/sysprogs/oracle/wls/122130:27141906]/ensure: change from 'absent' to 'present' failed: Could not set 'present' on ensure: Error while executing opatch command (file: /opt/puppetlabs/puppet/modules/orawls/manifests/opatch.pp, line: 55)

This is the log:
[oracle@hg65g72 modules]$ cat /sysprogs/oracle/wls/122130/cfgtoollogs/opatch/opatch2019-05-20_12-42-22PM_1.log
[May 20, 2019 12:42:27 PM] [INFO]   ZOP-50: The patch location is not valid because it may not exist (or) current user has no permission to access it. Please check the same.
[May 20, 2019 12:42:27 PM] [SEVERE] OUI-67135:Argument(s) Error... Patch Location not valid
[May 20, 2019 12:42:27 PM] [INFO]   Please check the arguments and try again.
[May 20, 2019 12:42:27 PM] [INFO]   Stack Description: java.lang.UnsupportedOperationException: Argument(s) Error... Patch Location not valid
[May 20, 2019 12:42:27 PM] [INFO]   StackTrace: oracle.opatch.OPatch.process(OPatch.java:804)
[May 20, 2019 12:42:27 PM] [INFO]   StackTrace: oracle.opatch.OPatch.main(OPatch.java:871)


I tryed applying it manualy according to your command:
/sysprogs/oracle/wls/122130/OPatch/opatch apply -silent -jre /sysprogs/oracle/java/current-jdk/jre -oh /sysprogs/oracle/wls/122130 /software/sysinstall/fmw/patches/27141906

and this succeeds any thoughts or other things to check?

**Comment by biemond** [comment]
Hi,

so download should be /software/sysinstall/fmw/patches/27141906 and not download_dir => '/software/sysinstall/fmw/patches',

**Comment by Joris29** [comment]
Ah ok thanks @biemond

**Comment by Joris29** [comment]
@biemond

Still getting the error with following config:

orawls::opatch {'27141906':
    ensure                    => 'present',
    oracle_product_home_dir   => '/sysprogs/oracle/wls/122130',
    jdk_home_dir              => '/sysprogs/oracle/java/current-jdk',
    patch_id                  => 27141906,
    patch_file                => '27141906',
    os_user                   => 'oracle',
    os_group                  => 'oinstall',
    download_dir              => '/software/sysinstall/fmw/patches/27141906',
    puppet_download_mnt_point => '/software/sysinstall/fmw/patches',
    remote_file               => false,
    log_output                => true,
    orainstpath_dir           => '/sysprogs/oraInventory',
    require                   => Orawls::Weblogic_type['fmw_infra'],
  }

**Comment by Joris29** [comment]
@biemond any thoughts?

I also tryed it with:
patch_file => '/software/sysinstall/fmw/patches/27141906',
And with:
puppet_download_mnt_point => '/software/sysinstall/fmw/patches/27141906',

But no luck and another question for wls_domain is it possible to change the IdentityType from jks to kks so this: [Use KSS For Demo] is checked?

**Comment by Joris29** [comment]
@biemond Sorry to bother you again but I would love this to be solved anything you can think of that can cause the error?

**Comment by biemond** [comment]
So can you re-produce it on this vagrant box https://github.com/biemond/biemond-orawls-vagrant-12.2.1-puppet4 

thanks

**Comment by Joris29** [comment]
@biemond i can't download all the software because i don't have an oracle account and another question how would this help me?

I tryed it on different machines even on a local vagrant machine and I always get the same error.

I will try to explain how my setup works:
- The opatch files are already extracted
- The extracted opatch folder is located at /software/sysinstall/fmw/patches/27141906
- I want the optach class to apply this already extracted folder
- I get the error:
Error: /Stage[main]/Intris2::System::Wls/Orawls::Opatch[27141906]/Wls_opatch[/sysprogs/oracle/wls/122130:27141906]/ensure: change from 'absent' to 'present' failed: Could not set 'present' on ensure: Error while executing opatch command (file: /opt/puppetlabs/puppet/modules/orawls/manifests/opatch.pp, line: 55)

This is the log:
[oracle@hg65g72 modules]$ cat /sysprogs/oracle/wls/122130/cfgtoollogs/opatch/opatch2019-05-20_12-42-22PM_1.log
[May 20, 2019 12:42:27 PM] [INFO] ZOP-50: The patch location is not valid because it may not exist (or) current user has no permission to access it. Please check the same.
[May 20, 2019 12:42:27 PM] [SEVERE] OUI-67135:Argument(s) Error... Patch Location not valid
[May 20, 2019 12:42:27 PM] [INFO] Please check the arguments and try again.
[May 20, 2019 12:42:27 PM] [INFO] Stack Description: java.lang.UnsupportedOperationException: Argument(s) Error... Patch Location not valid
[May 20, 2019 12:42:27 PM] [INFO] StackTrace: oracle.opatch.OPatch.process(OPatch.java:804)
[May 20, 2019 12:42:27 PM] [INFO] StackTrace: oracle.opatch.OPatch.main(OPatch.java:871)

orawls::opatch {'27141906':
ensure => 'present',
oracle_product_home_dir => '/sysprogs/oracle/wls/122130',
jdk_home_dir => '/sysprogs/oracle/java/current-jdk',
patch_id => 27141906,
patch_file => '27141906',  
// I tryed /software/sysinstall/fmw/patches/27141906
download_dir => '/software/sysinstall/fmw/patches/27141906', 
// I tryed /software/sysinstall/fmw/patches
puppet_download_mnt_point => '/software/sysinstall/fmw/patches',
// I tryed /software/sysinstall/fmw/patches/27141906
}

**Comment by biemond** [comment]
hi, 
that why you I ask you to use mine. I don't trust your config, it looks like a config error and I don't see any  opatch error.
But let me try to add your patch.
