### ISSUE TITLE
Cannot set frontEndHost & frontEnd ports on a Managed server

### ISSUE THREAD

**Issue by JoshiiSinfield** [biemond/biemond-orawls#72]
Hi,

It's not possible to set frontEndHost & ports on a managed server.

I'll take a stab at adding it in, just wanted to add this issue to keep track of it!

Thanks,
Josh

**Comment by robh007** [comment]
Hi Edwin, I'm going to send a PR for this. As suggested above I've copied the files from the wls_cluster type into shared. I've modified the files in shared not to not include the easytype validators name. I think the wls_cluster implementation isn't idempotent. Because there isn't a way to remove the frontend host name and if you try to set it to have a blank value or '' I think the validator is then spotting this and reporting an error. What I've done I think allows for setting the initial frontendhost and with the ability to remove and also you can change. If it's not what you would like to see let me know and I can change to suit. 

Thanks 

Rob.

**Comment by JoshiiSinfield** [comment]
Closing this as my colleague Rob uploaded a PR which was merged a while ago.

Cheers,
Josh
