### ISSUE TITLE
wls_group check if group exists

### ISSUE THREAD

**Issue by adamjk-dev** [biemond/biemond-orawls#93]
Can you update the wls_group provider to check to see if the group already exists? 

I think all you need to do is change: 
<code>
atnr.createGroup(name,description)
</code>
to:
<code>
if not atnr.groupExists(name):atnr.createGroup(name,description)
</code>

It will add the group and add users to it if it doesn't exist. Otherwise, It will just add the users to the existing group.

Looks like in this file:
https://github.com/biemond/biemond-orawls/blob/master/files/providers/wls_group/create.py.erb

**Comment by joewimmer** [comment]
```
user_instances:
  'test':
    ensure:                 'present'
    password:               *domain_wls_password
    authenticationprovider: 'DefaultAuthenticator'
    realm:                  'myrealm'
    description:            'test user'

group_instances:
  'Administrators':
    ensure:                 'present'
    authenticationprovider: 'DefaultAuthenticator'
    description:            'Administrators can view and modify all resource attributes and start and stop servers.'
    realm:                  'myrealm'
    users:
      - 'ser_dvapp'
    require:
      - Wls_user[test]
```

Above is our hiera data to add user test into group administrators, however the wls_group resource is not the cause of the issue we are seeing.  Below is our debug output as and error from your create.py.erb script.  

The error is generated because we are trying to create a group that already exists.  

```
Debug: wls:/JOETEST/serverConfig> create group:  Administrators

Debug: Unexpected error: weblogic.management.utils.AlreadyExistsException

Debug: ~~~~COMMAND FAILED~~~~

Error: Could not set 'present' on ensure: command in deamon failed.

```

May I suggest a fix of checking to see if a group already exists before trying to create it again.

OR 

Catch an already exists exception in the create.py.erb in the wls_group provider.  

Thanks!

**Comment by adamjk-dev** [comment]
Submitted pull request for this: https://github.com/biemond/biemond-orawls/pull/102

**Comment by biemond** [comment]
Hi,

I will never do that because you should not be in that situation, There is probably an error or misconfiguration. I think the group index py script crashes and this will occur in every puppet run but you don't see it.

So this is not a fix , but some workaround you won't want.
